version: "3"
services: 
    api:
        container_name: api_node_curso
        restart: always
        build: .
        ports: 
            - "5000:5000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: db_mongo_curso
        image: mongo
        ports: 
            - "27018:27017"
        logging: 
            driver: none